# Generated by Django 4.2.1 on 2023-08-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='urls',
            field=models.CharField(max_length=1000),
        ),
    ]
